name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: zhenyang7838675
          MYSQL_DATABASE: clod01
        ports:
          - 3306:3306
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Change Directory to helloworld
      run: cd helloWorld
    - name: Build with Maven
      run: mvn clean install

    - name: Run Integration Tests
      run: mvn test
