name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: zhenyang7838675
          MYSQL_DATABASE: clod01_test
        ports:
          - 3306:3306
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
   
    # - name: Build with Maven
    #   run: mvn clean install
    #   working-directory: helloworld

    # - name: Run Integration Tests
    #   run: mvn test
    #   working-directory: helloworld
    - name: Run Integration Tests in helloWorld
      run: bash helloWorld/run-test.sh
